baseurl = "/"
title = "WestGrid Training Modules 2021"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "manni"   # Chroma Style Gallery https://xyproto.github.io/splash/docs/longer/all.html

[params]
 repourl = "https://github.com/WestGrid/wgtm21"
 info = "Training Modules 2021"
 wgavatar = "/img/wglogo.png"
 favicon_32 = "/img/favicon.png"
 footercontent = "Information"
 dateformat = "January 2, 2006"
 hideCredits = false
 hideCopyright = false
 since = 2021

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Basics"
            weight = 1
            url = "basics"

            [[languages.en.menu.main]]
            name = "Programming"
            weight = 2
            url = "programming"

            [[languages.en.menu.main]]
            name = "Parallel"
            weight = 3
            url = "parallel"

            [[languages.en.menu.main]]
            name = "Cloud"
            weight = 4
            url = "cloud"

            [[languages.en.menu.main]]
            name = "ML"
            weight = 5
            url = "ml"

	    [[languages.en.menu.main]]
	    name = "SciVis"
	    weight = 6
	    url  = "scivis"

	    [[languages.en.menu.main]]
	    name = "MATLAB"
	    weight = 7
	    url  = "matlab"
